//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbs.Views.StudentMinistry {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StudentMinstryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentMinstryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ccbs.Views.StudentMinistry.StudentMinstryResources", typeof(StudentMinstryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有的新生列表.
        /// </summary>
        public static string ASL_Title {
            get {
                return ResourceManager.GetString("ASL_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 临住志愿者信息.
        /// </summary>
        public static string Cart_HostInfo {
            get {
                return ResourceManager.GetString("Cart_HostInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接机志愿者信息.
        /// </summary>
        public static string Cart_PickupInfo {
            get {
                return ResourceManager.GetString("Cart_PickupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动注册管理.
        /// </summary>
        public static string CP_Activities {
            get {
                return ResourceManager.GetString("CP_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统管理员工具.
        /// </summary>
        public static string CP_AdminTools {
            get {
                return ResourceManager.GetString("CP_AdminTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日程表管理.
        /// </summary>
        public static string CP_Calendar {
            get {
                return ResourceManager.GetString("CP_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新生事工资料下载.
        /// </summary>
        public static string CP_Download {
            get {
                return ResourceManager.GetString("CP_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看组员的接待情况.
        /// </summary>
        public static string CP_Group_Members {
            get {
                return ResourceManager.GetString("CP_Group_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新生Local Help.
        /// </summary>
        public static string CP_LocalHelp {
            get {
                return ResourceManager.GetString("CP_LocalHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理我的小组.
        /// </summary>
        public static string CP_Manage_Group {
            get {
                return ResourceManager.GetString("CP_Manage_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理我的机构.
        /// </summary>
        public static string CP_Manage_Org {
            get {
                return ResourceManager.GetString("CP_Manage_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页照片管理.
        /// </summary>
        public static string CP_Manage_Photos {
            get {
                return ResourceManager.GetString("CP_Manage_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户权限管理.
        /// </summary>
        public static string CP_ManageAccounts {
            get {
                return ResourceManager.GetString("CP_ManageAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会议记录管理.
        /// </summary>
        public static string CP_Meeting {
            get {
                return ResourceManager.GetString("CP_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作流程管理.
        /// </summary>
        public static string CP_News {
            get {
                return ResourceManager.GetString("CP_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择接机或临住的新生.
        /// </summary>
        public static string CP_SelectTask {
            get {
                return ResourceManager.GetString("CP_SelectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新生信息管理.
        /// </summary>
        public static string CP_StudentManage {
            get {
                return ResourceManager.GetString("CP_StudentManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统邮件管理.
        /// </summary>
        public static string CP_SystemEmail {
            get {
                return ResourceManager.GetString("CP_SystemEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制面板.
        /// </summary>
        public static string CP_Title {
            get {
                return ResourceManager.GetString("CP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 志愿者机构管理.
        /// </summary>
        public static string CP_VolunteerOrgs {
            get {
                return ResourceManager.GetString("CP_VolunteerOrgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的首页.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的临住列表.
        /// </summary>
        public static string My_Housing_List {
            get {
                return ResourceManager.GetString("My_Housing_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的接机列表.
        /// </summary>
        public static string My_Pickup_List {
            get {
                return ResourceManager.GetString("My_Pickup_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改密码.
        /// </summary>
        public static string PI_ChangePsw {
            get {
                return ResourceManager.GetString("PI_ChangePsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑信息.
        /// </summary>
        public static string PI_Edit {
            get {
                return ResourceManager.GetString("PI_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string PI_Email {
            get {
                return ResourceManager.GetString("PI_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string PI_Name {
            get {
                return ResourceManager.GetString("PI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机.
        /// </summary>
        public static string PI_Phone {
            get {
                return ResourceManager.GetString("PI_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人信息.
        /// </summary>
        public static string PI_Title {
            get {
                return ResourceManager.GetString("PI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新生提问的问题.
        /// </summary>
        public static string QandA_Title {
            get {
                return ResourceManager.GetString("QandA_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 到达.
        /// </summary>
        public static string SL_Arrive {
            get {
                return ResourceManager.GetString("SL_Arrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 来自.
        /// </summary>
        public static string SL_ComeFrom {
            get {
                return ResourceManager.GetString("SL_ComeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航班.
        /// </summary>
        public static string SL_Flight {
            get {
                return ResourceManager.GetString("SL_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string SL_Gender {
            get {
                return ResourceManager.GetString("SL_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回我的首页.
        /// </summary>
        public static string SL_GoBack {
            get {
                return ResourceManager.GetString("SL_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 临住情况.
        /// </summary>
        public static string SL_HousingStatus {
            get {
                return ResourceManager.GetString("SL_HousingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 专业.
        /// </summary>
        public static string SL_Major {
            get {
                return ResourceManager.GetString("SL_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string SL_Name {
            get {
                return ResourceManager.GetString("SL_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string SL_Note {
            get {
                return ResourceManager.GetString("SL_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接机情况.
        /// </summary>
        public static string SL_PickupStatus {
            get {
                return ResourceManager.GetString("SL_PickupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示所有新生.
        /// </summary>
        public static string SL_ShowAll {
            get {
                return ResourceManager.GetString("SL_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示统计结果.
        /// </summary>
        public static string SL_ShowStatistics {
            get {
                return ResourceManager.GetString("SL_ShowStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示尚分配完的新生.
        /// </summary>
        public static string SL_ShowUnassigned {
            get {
                return ResourceManager.GetString("SL_ShowUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择接机或者临住的新生.
        /// </summary>
        public static string SL_Title {
            get {
                return ResourceManager.GetString("SL_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 各小组统计.
        /// </summary>
        public static string Stat_Group {
            get {
                return ResourceManager.GetString("Stat_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小组.
        /// </summary>
        public static string Stat_GroupName {
            get {
                return ResourceManager.GetString("Stat_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成临住.
        /// </summary>
        public static string Stat_Housing {
            get {
                return ResourceManager.GetString("Stat_Housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 各志愿者机构学生事工统计.
        /// </summary>
        public static string Stat_Org {
            get {
                return ResourceManager.GetString("Stat_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 机构.
        /// </summary>
        public static string Stat_OrgName {
            get {
                return ResourceManager.GetString("Stat_OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成接机.
        /// </summary>
        public static string Stat_Pickup {
            get {
                return ResourceManager.GetString("Stat_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新生数量.
        /// </summary>
        public static string Stat_StudNum {
            get {
                return ResourceManager.GetString("Stat_StudNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务完成情况统计.
        /// </summary>
        public static string Stat_Title {
            get {
                return ResourceManager.GetString("Stat_Title", resourceCulture);
            }
        }
    }
}
