//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbs.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ccbs.Views.Home.HomeResources", typeof(HomeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登陆成功！.
        /// </summary>
        public static string Log_On_Success {
            get {
                return ResourceManager.GetString("Log_On_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新生注册.
        /// </summary>
        public static string Reg_NewStudent {
            get {
                return ResourceManager.GetString("Reg_NewStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新生接机和临住注册.
        /// </summary>
        public static string Reg_Tite {
            get {
                return ResourceManager.GetString("Reg_Tite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 志愿者注册.
        /// </summary>
        public static string Reg_Volunteer {
            get {
                return ResourceManager.GetString("Reg_Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 百科最新更新.
        /// </summary>
        public static string Section_BNs_Title {
            get {
                return ResourceManager.GetString("Section_BNs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 百科推荐文章.
        /// </summary>
        public static string Section_BRs_Title {
            get {
                return ResourceManager.GetString("Section_BRs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统登录.
        /// </summary>
        public static string Section_LogOn_Title {
            get {
                return ResourceManager.GetString("Section_LogOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 近期活动.
        /// </summary>
        public static string Section_RAs_Title {
            get {
                return ResourceManager.GetString("Section_RAs_Title", resourceCulture);
            }
        }
    }
}
