//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbs.Views.Volunteer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VolunteerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VolunteerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ccbs.Views.Volunteer.VolunteerResources", typeof(VolunteerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string Edit_Back {
            get {
                return ResourceManager.GetString("Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑失败，请更正下列错误.
        /// </summary>
        public static string Edit_Error {
            get {
                return ResourceManager.GetString("Edit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑个人信息.
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住址: APT /City /State /Zip code.
        /// </summary>
        public static string Reg_Address {
            get {
                return ResourceManager.GetString("Reg_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码确认.
        /// </summary>
        public static string Reg_ConfirmPsw {
            get {
                return ResourceManager.GetString("Reg_ConfirmPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string Reg_Email {
            get {
                return ResourceManager.GetString("Reg_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册出错啦！ 请更正下面的错误.
        /// </summary>
        public static string Reg_Error {
            get {
                return ResourceManager.GetString("Reg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string Reg_Gender {
            get {
                return ResourceManager.GetString("Reg_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您属于该机构的哪个小组？(若无分组则忽略).
        /// </summary>
        public static string Reg_Group {
            get {
                return ResourceManager.GetString("Reg_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您可以为新生提供哪种帮助？.
        /// </summary>
        public static string Reg_HelpType {
            get {
                return ResourceManager.GetString("Reg_HelpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名: Last, First.
        /// </summary>
        public static string Reg_Name {
            get {
                return ResourceManager.GetString("Reg_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任何需要特殊说明的吗?.
        /// </summary>
        public static string Reg_Note {
            get {
                return ResourceManager.GetString("Reg_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您是下面哪个机构的志愿者？.
        /// </summary>
        public static string Reg_Org {
            get {
                return ResourceManager.GetString("Reg_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果其他，请填写.
        /// </summary>
        public static string Reg_OtherRelation {
            get {
                return ResourceManager.GetString("Reg_OtherRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该机构(小组)的Access Code(如果您是UTD FACSS的志愿者，可忽略).
        /// </summary>
        public static string Reg_Passcode {
            get {
                return ResourceManager.GetString("Reg_Passcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机号: xxx-xxx-xxxx.
        /// </summary>
        public static string Reg_Phone {
            get {
                return ResourceManager.GetString("Reg_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人信息.
        /// </summary>
        public static string Reg_PI {
            get {
                return ResourceManager.GetString("Reg_PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下面哪一个最准确的描述您和UTD的关系？.
        /// </summary>
        public static string Reg_RelationToUTD {
            get {
                return ResourceManager.GetString("Reg_RelationToUTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人简介(optional).
        /// </summary>
        public static string Reg_SelfIntro {
            get {
                return ResourceManager.GetString("Reg_SelfIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交注册.
        /// </summary>
        public static string Reg_Submit {
            get {
                return ResourceManager.GetString("Reg_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 志愿者注册表格.
        /// </summary>
        public static string Reg_Title {
            get {
                return ResourceManager.GetString("Reg_Title", resourceCulture);
            }
        }
    }
}
