//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Published = false;
            this.Comments = new HashSet<ArticleComment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string MainContent { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int SubDirectoryId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Creator { get; set; }
        public int Number { get; set; }
        public bool Published { get; set; }
        public int LikeCount { get; set; }
        public int VisitCount { get; set; }
    
        public virtual SubDirectory Directory { get; set; }
        public virtual ICollection<ArticleComment> Comments { get; set; }
    }
}
