//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleComment
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int ArticleId { get; set; }
        public int LikeCount { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
