//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ccbs.Models
{
    public partial class BangbangDBContainer : DbContext
    {
        public BangbangDBContainer()
            : base("name=BangbangDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BBUser> BBUsers { get; set; }
        public DbSet<BBActivity> BBActivities { get; set; }
        public DbSet<BBRegisterEntry> BBRegisterEntries { get; set; }
        public DbSet<BBComment> BBComments { get; set; }
        public DbSet<BBCategory> BBCategories { get; set; }
        public DbSet<Location> Locations { get; set; }
    }
}
