//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class BBActivity
    {
        public BBActivity()
        {
            this.BBRegisterEntries = new HashSet<BBRegisterEntry>();
            this.BBComments = new HashSet<BBComment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int BBUserId { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool IsDraft { get; set; }
        public int BBCategoryId { get; set; }
    
        public virtual ICollection<BBRegisterEntry> BBRegisterEntries { get; set; }
        public virtual BBUser Creater { get; set; }
        public virtual ICollection<BBComment> BBComments { get; set; }
        public virtual BBCategory BBCategory { get; set; }
    }
    
}
