//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class BBCategory
    {
        public BBCategory()
        {
            this.BBActivities = new HashSet<BBActivity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<BBActivity> BBActivities { get; set; }
    }
    
}
