//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class BBRegisterEntry
    {
        public BBRegisterEntry()
        {
            this.RegisteredBBUsers = new HashSet<BBUser>();
        }
    
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public int UpCount { get; set; }
        public int LowerCount { get; set; }
        public int GenderLimit { get; set; }
        public bool IsActive { get; set; }
        public int BBActivityId { get; set; }
    
        public virtual BBActivity BBActivity { get; set; }
        public virtual ICollection<BBUser> RegisteredBBUsers { get; set; }
    }
    
}
