//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class BBUser
    {
        public BBUser()
        {
            this.CreatedActivities = new HashSet<BBActivity>();
            this.BBRegisterEntries = new HashSet<BBRegisterEntry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Major { get; set; }
        public int Year { get; set; }
        public string Avatar { get; set; }
        public string Username { get; set; }
        public string ComeFrom { get; set; }
        public System.DateTime RegTime { get; set; }
        public int LocationId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BBActivity> CreatedActivities { get; set; }
        public virtual ICollection<BBRegisterEntry> BBRegisterEntries { get; set; }
        public virtual Location Location { get; set; }
    }
    
}
