//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coworker
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string SelfIntro { get; set; }
        public string Testimony { get; set; }
        public string MindRenew { get; set; }
        public string Service { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string SelfPhoto { get; set; }
        public string BaptisePhoto { get; set; }
        public string Username { get; set; }
    }
}
