//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAccount
    {
        public EmailAccount()
        {
            this.DailyCounts = new HashSet<DailyCount>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Host { get; set; }
        public int Port { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string From { get; set; }
        public int SmtpDailyLimit { get; set; }
        public int SmtpPerTimeLimit { get; set; }
        public bool Verified { get; set; }
        public System.DateTime LastVerifyDate { get; set; }
        public string VerifyMessage { get; set; }
    
        public virtual ICollection<DailyCount> DailyCounts { get; set; }
    }
}
