//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class FacssDepartment
    {
        public FacssDepartment()
        {
            this.AppliedNewStudents = new HashSet<NewStudent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Introduction { get; set; }
        public bool IsOpenForApply { get; set; }
        public string ApplyNotification { get; set; }
    
        public virtual ICollection<NewStudent> AppliedNewStudents { get; set; }
    }
    
}
