//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class Group
    {
        public Group()
        {
            this.NewStudents = new HashSet<NewStudent>();
            this.Volunteers = new HashSet<Volunteer>();
            this.HostedStudents = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Passcode { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Volunteer Leader { get; set; }
        public virtual ICollection<NewStudent> NewStudents { get; set; }
        public virtual ICollection<Volunteer> Volunteers { get; set; }
        public virtual ICollection<Student> HostedStudents { get; set; }
    }
    
}
