//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class GuestParticipant
    {
        public GuestParticipant()
        {
            this.IsChristian = false;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public bool IsChristian { get; set; }
        public int RegisterEntryId { get; set; }
    
        public virtual RegisterEntry RegisterEntry { get; set; }
    }
    
}
