//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class OperationRecord
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public int Arg1 { get; set; }
        public int Arg2 { get; set; }
        public string Data { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
    }
    
}
