//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class Organization
    {
        public Organization()
        {
            this.Description = "Not Provided";
            this.NewStudents = new HashSet<NewStudent>();
            this.OrgRequests = new HashSet<OrgRequest>();
            this.Volunteers = new HashSet<Volunteer>();
            this.Groups = new HashSet<Group>();
            this.LocalHelps = new HashSet<LocalHelp>();
            this.HostedStudents = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Passcode { get; set; }
        public int ModelType { get; set; }
    
        public virtual ICollection<NewStudent> NewStudents { get; set; }
        public virtual Volunteer OrgLeader { get; set; }
        public virtual ICollection<OrgRequest> OrgRequests { get; set; }
        public virtual ICollection<Volunteer> Volunteers { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<LocalHelp> LocalHelps { get; set; }
        public virtual ICollection<Student> HostedStudents { get; set; }
    }
    
}
