//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class RegConf
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string State { get; set; }
        public System.DateTime ToggleDate { get; set; }
        public string NextState { get; set; }
    }
    
}
