//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class RegisterEntry
    {
        public RegisterEntry()
        {
            this.NewStudents = new HashSet<NewStudent>();
            this.GuestParticipants = new HashSet<GuestParticipant>();
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public bool IsActive { get; set; }
        public int LocalHelpId { get; set; }
    
        public virtual ICollection<NewStudent> NewStudents { get; set; }
        public virtual ICollection<GuestParticipant> GuestParticipants { get; set; }
        public virtual LocalHelp LocalHelp { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
    
}
