//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.SubItems = new HashSet<SectionSubItem>();
            this.GalleryItems = new HashSet<GalleryItem>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int Capacity { get; set; }
        public bool IsOnHomePage { get; set; }
        public int Order { get; set; }
        public string TitleColor { get; set; }
    
        public virtual ICollection<SectionSubItem> SubItems { get; set; }
        public virtual ICollection<GalleryItem> GalleryItems { get; set; }
    }
}
