//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionSubItem
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Link { get; set; }
        public int Type { get; set; }
        public int SectionId { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
