//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ccbs.Models
{
    public partial class Student
    {
        public Student()
        {
            this.RegisterEntries = new HashSet<RegisterEntry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Major { get; set; }
        public int Year { get; set; }
        public string Term { get; set; }
        public string ComeFrom { get; set; }
        public string CnName { get; set; }
        public string UserName { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual Volunteer PickupVolunteer { get; set; }
        public virtual Volunteer HostVolunteer { get; set; }
        public virtual Organization HostOrganization { get; set; }
        public virtual Group HostGroup { get; set; }
        public virtual ManualVolunteer ManualPickupVolunteer { get; set; }
        public virtual ManualVolunteer ManualHostVolunteer { get; set; }
        public virtual ICollection<RegisterEntry> RegisterEntries { get; set; }
    }
    
}
