//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebModelContainer : DbContext
    {
        public WebModelContainer()
            : base("name=WebModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activity> Activities { get; set; }
        public DbSet<SMMessage> SMMessages { get; set; }
        public DbSet<Coworker> Coworkers { get; set; }
        public DbSet<Meeting> Meetings { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Paragraph> Paragraphs { get; set; }
        public DbSet<HomeGallery> HomeGalleries { get; set; }
        public DbSet<EmailRecord> EmailRecords { get; set; }
        public DbSet<SubDirectory> SubDirectories { get; set; }
        public DbSet<Article> Articles { get; set; }
        public DbSet<ArticleComment> ArticleComments { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<Answer> Answers { get; set; }
        public DbSet<EmailAccount> EmailAccounts { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<SectionSubItem> SectionSubItems { get; set; }
        public DbSet<GalleryItem> GalleryItems { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Merchant> Merchants { get; set; }
    }
}
