//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UTDBaikeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UTDBaikeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UTDBaikeResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘记密码？.
        /// </summary>
        internal static string LogOn_ForgetPsw {
            get {
                return ResourceManager.GetString("LogOn_ForgetPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        internal static string LogOn_Password {
            get {
                return ResourceManager.GetString("LogOn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        internal static string LogOn_Register {
            get {
                return ResourceManager.GetString("LogOn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string LogOn_Submit {
            get {
                return ResourceManager.GetString("LogOn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统登录.
        /// </summary>
        internal static string LogOn_Title {
            get {
                return ResourceManager.GetString("LogOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        internal static string LogOn_UserName {
            get {
                return ResourceManager.GetString("LogOn_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 论坛.
        /// </summary>
        internal static string Menu_BBS {
            get {
                return ResourceManager.GetString("Menu_BBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系我们.
        /// </summary>
        internal static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        internal static string Menu_HomePage {
            get {
                return ResourceManager.GetString("Menu_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的主页.
        /// </summary>
        internal static string Menu_MyPage {
            get {
                return ResourceManager.GetString("Menu_MyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新生问问.
        /// </summary>
        internal static string Menu_QandA {
            get {
                return ResourceManager.GetString("Menu_QandA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        internal static string Menu_RegisterPage {
            get {
                return ResourceManager.GetString("Menu_RegisterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTD百科.
        /// </summary>
        internal static string Menu_UTDBaike {
            get {
                return ResourceManager.GetString("Menu_UTDBaike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTD 生活百科.
        /// </summary>
        internal static string Website_Title {
            get {
                return ResourceManager.GetString("Website_Title", resourceCulture);
            }
        }
    }
}
